import { readdirSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { createHash } from 'node:crypto'
import { defineConfig, type Plugin } from 'vite'

// GitHub Pages serves this as a project site under /games/, so asset URLs need
// that prefix there; other hosts (e.g. Vercel) serve from the domain root.
const base = process.env.GITHUB_PAGES ? '/games/' : '/'

/** Every fetched file under public/, as a base-prefixed URL. */
function publicUrls(dir = 'public', prefix = ''): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) return publicUrls(full, `${prefix}${entry}/`)
    // Licence and readme files ride along for attribution but are never fetched.
    if (/\.(txt|md)$/i.test(entry)) return []
    return [`${base}${prefix}${entry}`]
  })
}

/**
 * Emits the web app manifest and a service worker that precaches the whole
 * game. Hand-rolled rather than pulled from a plugin because the asset set is
 * small and fully known at build time — the precache list is the bundle plus
 * public/, and everything else fits in a one-line fetch strategy.
 */
function pwa(): Plugin {
  return {
    name: 'game-pwa',
    apply: 'build',
    generateBundle(_options, bundle) {
      const built = Object.keys(bundle).map((file) => `${base}${file}`)
      const precache = [base, ...built, ...publicUrls()]
      // Any change to the file list or their hashed names rotates the cache,
      // which is what evicts the previous deploy on activate.
      const version = createHash('sha256').update(precache.join('\n')).digest('hex').slice(0, 12)

      this.emitFile({
        type: 'asset',
        fileName: 'manifest.webmanifest',
        source: JSON.stringify(
          {
            name: 'Incremental RPG',
            short_name: 'RPG',
            description: 'Train your hero and clear every stage.',
            start_url: base,
            scope: base,
            display: 'standalone',
            orientation: 'portrait',
            background_color: '#ffe9f0',
            theme_color: '#ff8fb1',
            icons: [
              { src: `${base}assets/icons/icon-192.png`, sizes: '192x192', type: 'image/png' },
              { src: `${base}assets/icons/icon-512.png`, sizes: '512x512', type: 'image/png' },
              {
                src: `${base}assets/icons/icon-maskable-512.png`,
                sizes: '512x512',
                type: 'image/png',
                purpose: 'maskable',
              },
            ],
          },
          null,
          2,
        ),
      })

      this.emitFile({ type: 'asset', fileName: 'sw.js', source: serviceWorker(version, precache) })
    },
  }
}

function serviceWorker(version: string, precache: string[]): string {
  return `// Generated by vite.config.ts — do not edit.
const CACHE = 'incremental-rpg-${version}'
const PRECACHE = ${JSON.stringify(precache, null, 2)}
const SHELL = ${JSON.stringify(base)}
// Static hosts commonly send "Vary: Origin". The precache is filled by URL, so
// those entries carry no Origin, while <script crossorigin> requests do — the
// default Vary check would then miss every chunk. Everything here is
// same-origin, so the header carries no meaning worth honouring.
const MATCH = { ignoreVary: true }

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  if (new URL(request.url).origin !== self.location.origin) return

  // Navigations try the network first so a new deploy is picked up as soon as
  // there is a connection, and fall back to the cached shell when offline.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone()
          caches.open(CACHE).then((cache) => cache.put(SHELL, copy))
          return response
        })
        .catch(() => caches.match(SHELL, MATCH).then((cached) => cached || Response.error())),
    )
    return
  }

  // Everything else is content-hashed or stable art: serve from cache and only
  // reach the network for something the precache missed.
  event.respondWith(
    caches.match(request, MATCH).then((cached) => {
      if (cached) return cached
      return fetch(request).then((response) => {
        if (response.ok && response.type === 'basic') {
          const copy = response.clone()
          caches.open(CACHE).then((cache) => cache.put(request, copy))
        }
        return response
      })
    }),
  )
})
`
}

export default defineConfig({
  base,
  plugins: [pwa()],
  build: {
    rollupOptions: {
      output: {
        // Phaser is most of the bundle and only changes when it is upgraded, so
        // splitting it keeps game-code deploys off the big cache entry.
        // Supabase deliberately has no group here: naming a group makes the
        // chunk a static import, which would undo the lazy load in
        // supabaseClient.ts. Its dynamic import already earns its own chunk.
        advancedChunks: {
          groups: [{ name: 'phaser', test: /[\\/]node_modules[\\/]phaser[\\/]/ }],
        },
      },
    },
  },
})
